# Generated by Django 4.2.5 on 2023-10-03 19:35

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to='uploads/')),
                ('title', models.CharField(max_length=220)),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Publish Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
    ]
